braun-embedded/stepper

- Cargo.toml
Alpha versions might introduce breaking changes, but Cargo will pick
them up automatically, as if they were semver-compatible. To prevent
breakage, the version needs to be pinned.
> Pin version of embedded-hal dependency

- Cargo.toml
- drivers/drv8825/Cargo.toml
- drivers/drv8825/README.md
- drivers/drv8825/src/drv8825.rs
- drivers/drv8825/src/lib.rs
- src/drv8825.rs
- src/lib.rs
I finally got around to doing some preliminary testing on this, and things are looking promising so far! I've confirmed I can step in either direction at this point, which is a good start. The step mode selection still needs to be tested and verified (I'm not sure I can accurately do this without a test stand), but I just wanted to get some eyes on this in the meantime.
I've included the `Enable`, `Fault`, and `Sleep` pins in the `DRV8825` struct, but they're not currently used for anything. These features can be added whenever `step-dir` has decided on a suitable abstraction for them, I just decided to include them for completeness.
There seems to be a fair bit of duplicate code between this driver and the STSPIN220 driver. It's probably still a bit early, but there may be some …
> Add a minimal driver implementation for the DRV8825

- Cargo.toml
This is in response to #7.
I was able to reproduce the errors in the [docs.rs build log](https://docs.rs/crate/step-dir/0.3.0/builds/314801) locally. These errors were resolved following the update of _embedded-time_ to `0.10.1`.
> Bump embedded-time version

- src/lib.rs
This is very useful, when making step calculations that include the
direction as the sign.
> Assign values to `Dir` variants

- drivers/drv8825/Cargo.toml
- drivers/drv8825/README.md
- drivers/drv8825/src/lib.rs
- drivers/stspin220/Cargo.toml
- drivers/stspin220/README.md
- drivers/stspin220/src/lib.rs
- src/driver.rs
- src/drivers/drv8825.rs
- src/drivers/mod.rs
- src/drivers/stspin220.rs
- src/lib.rs
- src/traits.rs
- templates/driver/src/lib.rs.tmpl
- test-stand/src/lib.rs
- test-stand/tests/tests/stspin220.rs
This is a first step towards reducing the duplication between drivers, as laid out in #31. I'm already working on the next few steps, but those turned out to be a bit more involved than I had assumed. I figure it's better to get this merged piecemeal, to keep each pull request digestible.
> Introduce `Driver` API

- src/driver.rs
- src/drivers/drv8825.rs
- src/drivers/stspin220.rs
- src/traits.rs
- test-stand/src/lib.rs
- test-stand/tests/tests/stspin220.rs
This pull request makes all driver state management available through the abstract `Driver` API, and further reduces the duplicated code between drivers (what's left is due to the drivers having similar structures and implementing the same traits).
This is not quite done. It still requires some testing, and CI will probably fail due to documentation and the test stand not being fully updated. I figured I'd still submit this as a draft, as the work week is over for me. I'll clean it up next week.
Blocked on #53.
Close #31
> Improve state management

- test-stand/Cargo.toml
All of my pull requests have been merged and a new version has been
released.
> Switch to upstream version of rotary-encoder-hal

- src/driver.rs
- src/drivers/drv8825.rs
- src/drivers/stspin220.rs
- test-stand/tests/tests/stspin220.rs
> Rename `Driver` constructor; update its documentation

- src/driver.rs
- test-stand/src/lib.rs
This provides a convenient way to access the pulse length, without
having to refer to the driver by name, or through a (possibly
cumbersome) generic parameter.
> Add function to `Driver` that returns pulse length

- src/drivers/drv8825.rs
- src/drivers/stspin220.rs
- src/lib.rs
- src/step_mode.rs
- src/traits.rs
- test-stand/tests/tests/stspin220.rs
The module contains a lot of types that use up a lot of real estate in
the top-level namespace. Making the module public makes more sense, I
think. It might also make sense to selectively re-export some of its
types, but I'm not sure about that yet.
> Make `step_mode` public, remove re-exports

- .github/workflows/ci-build.yml
- CONTRIBUTING.md
- README.md
- drivers/drv8825/README.md
- drivers/stspin220/README.md
- templates/driver/README.md.tmpl
- test-stand/README.md
There's a political argument for changing the name of the main branch
from `master` to `main`. I don't know what to think about that, so I'm
going to ignore it for my following arguments.
I think "main" is clearly the better name for the main/master branch:
- It is shorter and has half the number of syllables.
- It is a much clearer name. At least to me as a non-native speaker, the
concept of a master record, which is the basis of the name "master",
as far as I understand, is much more obscure than "main", which is a
basic and pervasive word.
Given that, I see the following two reasons to stay with master:
1. The change is perceived as part of a political movement that induces
a counter-reaction in many people.
2. "master" is the already established name, and changing it might lead
to …
> Change main branch name to `main`

- src/driver/mod.rs
- src/driver/set_direction.rs
- src/driver/set_step_mode.rs
- src/driver/step.rs
- src/drivers/drv8825.rs
- src/drivers/stspin220.rs
- src/lib.rs
- src/traits.rs
- test-stand/src/lib.rs
- test-stand/tests/tests/stspin220.rs
Also updates a bunch of references to it around the code base.
> Rename `Driver` to `Stepper`

- src/lib.rs
- src/stepper/mod.rs
- src/stepper/set_direction.rs
- src/stepper/set_step_mode.rs
- src/stepper/step.rs
- test-stand/tests/tests/stspin220.rs
Establishes a consistent nomenclature, and updates documentation, method names etc. accordingly. This is more fallout from #83.
> Clarify nomenclature used by `Stepper`

- Cargo.toml
- src/lib.rs
I'm going to need this in an upcoming pull request I'm currently working
on, but it seems like a reasonable addition on its own.
> Add constructor to convert velocity to `Direction`

- src/lib.rs
- src/stepper/mod.rs
- src/stepper/set_direction.rs
- src/stepper/set_step_mode.rs
- src/stepper/step.rs
- src/util/mod.rs
- src/util/ref_mut.rs
I'm working on a higher-level API that should be implementable for motion control chips, but also have a software fallback for regular STEP/DIR drivers. In implementing this software fallback, I find the need to re-use parts of `Stepper` (for architectural reasons, I can't use the `Stepper` API in this fallback implementation).
This series of commits makes the API of the future types more flexible, so I can re-use them in the motion control fallback implementation.
> Make futures more flexible

- src/stepper/set_direction.rs
- src/stepper/set_step_mode.rs
- src/stepper/step.rs
Otherwise it's easy to forget them, especially for those unfamiliar with
the API.
> Make futures `#[must_use]`

- Cargo.toml
- src/lib.rs
- src/motion_control.rs
- src/stepper/mod.rs
- src/stepper/move_to.rs
- src/traits.rs
- src/util/ref_mut.rs
Defines motion control traits that drivers can implement, a high-level interface for `Stepper` that uses those traits, as well as a fallback implementation for drivers that don't support this in software (i.e. all of the currently supported ones) based on [RampMaker](https://github.com/flott-motion/ramp-maker).
As of now, there are some problems that I'd like to address in follow-up PRs:
- The target step is unsigned and direction is defined by the sign of the velocity. I think this is weird, and I don't remember why I did it that way (I've started working on this a while ago, before I implemented the required changes in RampMaker).
- The motion control API does not track the position internally, meaning the target step is always relative to the current position. This is not in line with …
> Add high-level motion control interface

- src/lib.rs
This provides convenience to users, who don't have to manage that
dependency themselves (and keep it in sync with the version used by
Step/Dir).
> Re-export `ramp_maker`

- src/lib.rs
- src/motion_control.rs
- src/stepper/mod.rs
- src/stepper/move_to.rs
- src/traits.rs
- src/util/ref_mut.rs
Updates the software motion control to track the current step, which allows the motion control API to accept an absolute target position instead of a relative one. From what I've seen, this is more in line with what motion control hardware provides.
> Change motion control API to accept absolute target position

- src/motion_control/error.rs
- src/motion_control/mod.rs
Makes `SetStepMode` functionality available through `SoftwareMotionControl`, both as a direct trait implementation and a convenience method.
> Support setting step more for software-motion-controlled driver

- src/motion_control/conversion.rs
- src/motion_control/error.rs
- src/motion_control/mod.rs
- src/motion_control/state.rs
Replaces the `TryInto` trait bound that required a custom numeric type with an explicit converter that must implement the new `DelayToTicks` trait.
> Remove the need for a custom numeric type

- src/motion_control/error.rs
- src/motion_control/mod.rs
- src/motion_control/state.rs
Remove all trait bounds from `motion_control::Error`, simplifying the enum significantly. This comes at the cost of more type parameters, but I believe the reduced complexity is worth it. It is already bearing fruit in this pull request, allowing for the replacement of the custom `Debug` implementation with a much simpler (and less error-prone) `#[derive(Debug)]`. It's also going to make some conversions I'd like to implement between error types much more practical.
> Simplify `motion_control::Error`

- Cargo.toml
- src/lib.rs
The high-level motion control interface is more powerful, more
convenient, and more universal (supported for all STEP/DIR drivers via
software fallback, as well as any motion control chips that will be
supported in the future). It makes sense to prefer it over the
lower-level interface in the documentation.
> Use motion control interface in example

- test-stand/src/lib.rs
The old name was really short, I assume because it would have otherwise
collided with the old name of `Stepper`.
> Rename type parameter

- Cargo.toml
- documentation/platform-support.md
- src/compat.rs
- src/lib.rs
This is currently blocked on https://github.com/FluenTech/embedded-time/pull/101 and a new release of `embedded-time`.
> Add compability code to broaden platform support

- .github/FUNDING.yml
I've updated my GitHub Sponsors profile to be focused on non-embedded
thing, and I don't want to mislead anyone.
> Remove GitHub Sponsors link

- .cargo-task/.gitignore
- Cargo.toml
- src/drivers/dq542ma.rs
- src/drivers/mod.rs
hi :smiley_cat: 
here's a pull request for a basic driver for the DQ542MA stepper motor driver. :seedling: 
i haven't tested this in the real-world yet, need to battle the compiler first to integrate this with `stm32f7xx-hal` and my code. :purple_heart:
> add DQ542MA driver

- Cargo.toml
- drivers/drv8825/Cargo.toml
- drivers/stspin220/Cargo.toml
- src/compat.rs
- src/drivers/dq542ma.rs
- src/drivers/drv8825.rs
- src/drivers/stspin220.rs
- src/lib.rs
- src/motion_control/conversion.rs
- src/motion_control/error.rs
- src/motion_control/mod.rs
- src/motion_control/state.rs
- src/stepper/error.rs
- src/stepper/mod.rs
- src/stepper/set_direction.rs
- src/stepper/set_step_mode.rs
- src/stepper/step.rs
- src/traits.rs
- src/util/ref_mut.rs
With all credit going to @ahdinosaur, this PR builds on top of #142 and supersedes it to replace `embedded-time` with `fugit`. It also ups use of `embedded-hal` to "=1.0.0-alpha.8" with associated changes to the introduced `ErrorTrait`. Lastly, due to breaking nature of changes, package versions are upped to `0.6.0`.
Thank you!
> PR #142 part deux: replace embedded-time with fugit

- Cargo.toml
- src/compat.rs
- src/drivers/dq542ma.rs
- src/drivers/drv8825.rs
- src/drivers/stspin220.rs
- src/lib.rs
- src/stepper/error.rs
- src/stepper/set_direction.rs
- src/stepper/step.rs
- src/traits.rs
Hi there,
I was working on a new driver for your framework (for the A4988), and I thought I'd get the `embedded-hal` dependencies on their most recent versions (`1.0.0-alpha.9` and `0.2.7`) to save you some trouble.
The changes required were pretty minor. Notably, `embedded-hal` now contains only blocking traits, and has changed their module paths to no longer reference `::blocking`.
https://github.com/rust-embedded/embedded-hal/blob/a55595cc80f19626f5db58abb6da619459064bf7/embedded-hal/CHANGELOG.md#changed
I'll follow this up with the driver code.  
Thanks!
> Upgrade to latest embedded-hal versions
